# Generated by Django 4.1.1 on 2022-09-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('famous', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famous',
            name='is_published',
        ),
    ]
