# Generated by Django 4.1.1 on 2022-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famous', '0002_remove_famous_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='famous',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
