# Generated by Django 4.1.1 on 2022-09-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famous', '0003_famous_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='famous',
            options={'ordering': ['-cat'], 'verbose_name': 'Famous people', 'verbose_name_plural': 'Famous people'},
        ),
        migrations.AddField(
            model_name='famous',
            name='photo',
            field=models.ImageField(default=False, upload_to='photos/%Y/%m,%d'),
        ),
    ]
